tuto10/blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='index'),
    path('service/', views.service, name='service'),
    path('portfolio/<slug:category>/<slug:client>/', views.portfolio, name='portfolio'),
    path('team/', views.TeamListView.as_view(), name='team'),
    path('project/<slug:id>/<slug:category>/<slug:client>/', views.project_detail, name='project_detail'),
    path('post/<slug:category>/', views.forum, name='post_list'),
    path('post/<slug:slug>/<int:year>/<int:month>/<int:day>/', views.post_detail, name='post_detail'),
    path('post/serach/', views.PostSearchListView.as_view(), name='post_search'),
    path('project/search/', views.project_search, name='project_search'),
    #path('project/serach/', views.ProjectSearchListView.as_view(), name='project_search'),

]

tuto10/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tuto10/blogs/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class PostCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Client(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField()
    resume = models.CharField(max_length=250)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='project_category')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='project_client')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blogs:project_detail', args=[self.id, self.category, self.client])

class Team(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    image = models.ImageField()
    job = models.CharField(max_length=50, default='?')
    facebook_url = models.URLField()
    twitter_url = models.URLField()
    linkedin_url = models.URLField()

    def __str__(self):
        return self.last_name

class Post(models.Model):
    STATUS_CHOICES = (
                ('draft', 'Draft'),
                ('published', 'Published'), )
    title = models.CharField(max_length=100)
    image = models.ImageField()
    resume = models.CharField(max_length=250)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    publish = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(max_length=250)
    status = models.CharField(max_length = 10, choices = STATUS_CHOICES, default ='draft')
    category = models.ForeignKey(PostCategory, on_delete=models.CASCADE, related_name='project_category', default = 1)



    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogs:post_detail', args=[self.slug, self.publish.year, self.publish.month, self.publish.day])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

tuto10/blogs/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

tuto10/blogs/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView
from django.views import generic
from django.shortcuts import render, get_object_or_404, redirect

from .models import Project, Team, Post

from django.core.paginator import Paginator

from django.db.models import Q

from .forms import CommentForm

def index(request):
    return render(request, 'blogs/index.html')

def service(request):
    return render(request, 'blogs/service.html')

def portfolio(request, category, client):
    if category == 'all' and client == 'all':
        projects = Project.objects.all()
    elif category == 'all':
        projects = Project.objects.filter(client__name = client)
    else:
        projects = Project.objects.filter(category__name = category)
    paginator = Paginator(projects, 3)
    page = request.GET.get('page')
    projects_page = paginator.get_page(page)
    return render(request, 'blogs/project_list.html', {'projects':projects_page})

class TeamListView(generic.ListView):
    model = Team
    context_object_name = 'teams'
    queryset = Team.objects.all()
    paginate_by = 1
    template_name = 'blogs/team.html'

def project_detail(request, id, category, client):
    project = get_object_or_404(Project, id=id, category__name = category, client__name = client)
    return render(request, 'blogs/project_detail.html', {'project':project})

def forum(request, category):
    if category == 'all':
        posts = Post.objects.filter(status='published')
    else:
        posts = Post.objects.filter(status='published', category__name = category)
    paginator = Paginator(posts, 3)
    page = request.GET.get('page')
    posts_page = paginator.get_page(page)
    return render(request, 'blogs/post_list.html', {'posts':posts_page})

def post_detail(request, slug, year, month, day):
    post = get_object_or_404(Post, slug=slug, publish__year = year, publish__month = month, publish__day = day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return HttpResponseRedirect(request.path)
    else:
        comment_form = CommentForm()
    return render(request, 'blogs/post_detail.html', {'post':post,'comments':comments,'comment_form':comment_form})

class PostSearchListView(generic.ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 1
    template_name = 'blogs/post_search.html'

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query is not None:
            queryset = Post.objects.filter((Q(title__icontains=query) | Q(resume__icontains=query)), status='published')
            return queryset
        else :
            return Post.objects.filter(status='published').none() # just an empty queryset as default

def project_search(request):
    if request.GET.get('query'):
        query_name =  request.GET.get('query')
        try:
            projects = Project.objects.filter(Q(name__icontains=query_name) | Q(resume__icontains=query_name))
            paginator = Paginator(projects, 2)
            page = request.GET.get('page')
            projects_page = paginator.get_page(page)
            return render(request,'blogs/project_search.html', {'projects': projects_page, 'query': query_name})
        except:
            return render(request,'blogs/project_search.html')
    else:
        return render(request,'blogs/project_search.html')



'''
class ProjectSearchListView(generic.ListView):
    model = Project
    context_object_name = 'projects'
    paginate_by = 1
    template_name = 'blogs/project_search.html'

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query is not None:
            queryset = Project.objects.filter(Q(name__icontains=query))
            return queryset
        else :
            return Project.objects.none() # just an empty queryset as default
'''

tuto10/blogs/templates/blogs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Agency - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blogs/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'blogs:index' %}"><img src="{% static 'blogs/assets/img/navbar-logo.svg' %}" alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'blogs:service' %}">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'blogs:portfolio' 'all' 'all' %}">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'blogs:team' %}">Team</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'blogs:post_list' 'all' %}">Forum</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        <!-- sections -->
        {% endblock %}

        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; Your Website 2021</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                        <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blogs/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

tuto10/blogs/templates/blogs/pagination_1.html
        {% load blog_tags %}
        <!-- pagination for views with generic ListView-->
        <div class="container" data-aos="fade-up">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="?{% url_replace page=1 %}">&laquo; first</a>
                            <a href="?{% url_replace page=page_obj.previous_page_number %}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="?{% url_replace page=page_obj.next_page_number %}">next</a>
                            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">last &raquo;</a>
                        {% endif %}
                        </span>
                    </div>
                    {% endif %}
                </ul>
            </nav>
        </div>  <!-- End pagination-->    

tuto10/blogs/templates/blogs/pagination_2.html
 {% load blog_tags %}
<!--pagination for viwes with function-->
<div class="container" data-aos="fade-up">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <div class="pagination">
                            <span class="step-links">
                                {% if page.has_previous %}
                                <a href="?{% url_replace page=1 %}">&laquo; first</a>
                                <a href="?{% url_replace page=page.previous_page_number %}">previous</a>
                                {% endif %}

                                <span class="current">
                                  Page {{ page.number }} of {{ page.paginator.num_pages }}.
                                </span>

                                {% if page.has_next %}
                                <a href="?{% url_replace page=page.next_page_number %}">next</a>
                                <a href="?{% url_replace page=page.paginator.num_pages %}">last &raquo;</a>
                                {% endif %}
                            </span>
                        </div>
                    </ul>
                </nav>
            </div>  <!-- End pagination-->

tuto10/blogs/templates/blogs/post_detail.html
{% extends "blogs/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<!-- Masthead-->
<header class="masthead">
  <div class="container">
    <div class="masthead-subheading">{{post.title}}</div>
  </div>
</header>


<section>
<!-- Forum post-->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-6 col-sm-4">
      <div class="modal-body">
        <!-- post details-->
        <h2 class="text-uppercase">{{post.title}}</h2>
        <img class="img-fluid d-block mx-auto" src="{{post.image.url}}" alt="..." />
        <p>{{post.content}}</p>
        <ul class="list-inline">
          <li>
            <strong>Author:</strong>
            {{post.author}}
          </li>
          <li>
            <strong>Date:</strong>
            {{post.publish}}
          </li>
        </ul>
      </div>
  <!-- post comment-->
<div class="card mb-4">
      {% with comments.count as total_comments %}
      <h4>{{ total_comments }} comment{{total_comments|pluralize }}</h4>
      {% endwith %}
      {% for comment in comments %}
      <div class="comment mt-4 text-justify float-left"> <img src="https://i.imgur.com/yTFUilP.jpg" alt="" class="rounded-circle" width="40" height="40">
          <h4>{{comment.name}}</h4> <span>- {{comment.created}}</span> <br>
          <p>{{comment.body}}</p>
      </div>
      {% endfor %}
  </div>
<div class="card mb-4">
      <h4>Leave a Comment</h4>
      <form method="post">
        {{ comment_form | crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
      </form>
  </div>
    </div>

    <!-- Side widgets-->
    <div class="col-lg-4">
      {% include "blogs/post_searchForm.html" %}
        <!-- Categories widget-->
      {% include "blogs/post_widget.html" %}
    </div>

  </div>
  </div>
</section>

{% endblock %}

tuto10/blogs/templates/blogs/post_search.html
{% extends "blogs/base.html" %}

{% block content %}

<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">Welcome To Our Forum!</div>
    </div>
</header>

<!-- Portfolio Grid-->
<section class="page-section bg-light" id="portfolio">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Forum</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <div class="row">
            <div class="col-lg-8 col-sm-6">
                {% for post in posts %}
                <!-- Portfolio item 6-->
                <div class="portfolio-item">
                    <div class="portfolio-caption">
                        <a>{{post.title}}</a>
                    </div>
                  <img class="img-fluid" src="{{post.image.url}}" alt="..." />
                    <div class="portfolio-caption">
                        <div class="portfolio-caption-subheading text-muted">{{post.resume}}</div>
                        <a href="{{ post.get_absolute_url }}">Read more</a>
                    </div>
                </div>
            {% endfor %}
            <!-- pagination -->
            {% include 'blogs/pagination_1.html'%}
            </div>
            <!-- search form -->
            {% include 'blogs/post_searchForm.html' %}


        </div>
    </div>
</section>

{% endblock %}

tuto10/blogs/templates/blogs/post_searchForm.html
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                  <form method='GET' class='' action="{% url 'blogs:post_search'%}">
                      <input type="text" name="query" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                      <button type="submit"><i class="fas fa-search"></i></button>
                  </form>
                </div>
            </div>

tuto10/blogs/templates/blogs/post_widget.html
{% load blog_tags %}
<div class="card mb-4">
    <div class="card-header">Categories</div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <ul class="list-unstyled mb-0">
                    {% show_list_postcategory as categories %}
                    {% for category in categories %}
                    <li><a href="{% url 'blogs:post_list' category.name %}">{{category.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="card mb-4">
    <div class="card-header">Most commented posts</div>
    <div class="card-body">
        <div class="row">
          {% get_most_commented_posts as commented %}
          {% for post in commented %}
          <div class="col-sm-6">
            <div class="card mb-4">
              <a href="{{ post.get_absolute_url }}"><img class="card-img-top" src="{{post.image.url}}" alt="..." /></a>
              <div class="card-body">
                <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
    </div>
</div>

tuto10/blogs/templates/blogs/project_detail.html
{% extends "blogs/base.html" %}

{% block content %}
        <!-- Portfolio Modals-->
<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">{{project.name}}</div>
    </div>
</header>
        <section>
  <div class="container">
                        <div class="row ">
                            <div class="col-lg-8">
                                <div class="modal-body">
                                    <!-- Project details-->
                                    <h2 class="text-uppercase">{{project.name}}</h2>
                                    <img class="img-fluid d-block mx-auto" src="{{project.image.url}}" alt="..." />
                                    <p>{{project.content}}</p>
                                    <ul class="list-inline">
                                        <li>
                                            <strong>Client:</strong>
                                            {{project.client}}
                                        </li>
                                        <li>
                                            <strong>Category:</strong>
                                            {{project.category}}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-4">
                            {% include "blogs/project_searchForm.html" %}
                          {% include "blogs/project_widget.html" %}
                          </div>
                        </div>
</div>
          </section>

    {% endblock %}

tuto10/blogs/templates/blogs/project_list.html
{% extends "blogs/base.html" %}

{% block content %}

<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">Welcome To Our Portfolio!</div>
    </div>
</header>

<!-- Portfolio Grid-->
<section class="page-section bg-light" id="portfolio">
    <div class="container">
        <div class="row">
          <div class="col-lg-8">
              <!-- Nested row for non-featured blog posts-->
              <div class="row">
                  {% for project in projects %}
                  <div class="col-lg-6">
                      <!-- Blog post-->
                      <div class="card mb-4">
                          <a href="#!"><img class="card-img-top" src="{{project.image.url}}" alt="..." /></a>
                          <div class="card-body">
                              <h2 class="card-title h4">{{project.name}}</h2>
                              <h2 class="card-title h4">Client: {{project.client}}</h2>
                              <h2 class="card-title h4">Category: {{project.category}}</h2>
                              <p class="card-text">{{project.resume}}</p>
                              <a class="btn btn-primary" href="{{project.get_absolute_url}}">Read more →</a>
                          </div>
                      </div>
                  </div>
                  {% endfor %}
              </div>
              <!-- Pagination-->
              {% include "blogs/pagination_2.html" with page=projects %}
          </div>
        <div class="col-lg-4">
        {% include "blogs/project_searchForm.html" %}
      {% include "blogs/project_widget.html" %}
      </div>
</div>
</section>

{% endblock %}

tuto10/blogs/templates/blogs/project_search.html
{% extends "blogs/base.html" %}

{% block content %}

<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">Welcome To Our Portfolio!</div>
    </div>
</header>

<!-- Portfolio Grid-->
<section class="page-section bg-light" id="portfolio">
    <div class="container">
        <div class="row">
          <div class="col-lg-8">
              <!-- Nested row for non-featured blog posts-->
              <div class="row">
                {% if projects %}
                <h1> The liste of project with the search term "{{query}}" are : </h1>
                  {% for project in projects %}
                  <div class="col-lg-6">
                      <!-- Blog post-->
                      <div class="card mb-4">
                          <a href="#!"><img class="card-img-top" src="{{project.image.url}}" alt="..." /></a>
                          <div class="card-body">
                              <h2 class="card-title h4">{{project.name}}</h2>
                              <h2 class="card-title h4">Client: {{project.client}}</h2>
                              <h2 class="card-title h4">Category: {{project.category}}</h2>
                              <p class="card-text">{{project.resume}}</p>
                              <a class="btn btn-primary" href="{{project.get_absolute_url}}">Read more →</a>
                          </div>
                      </div>
                  </div>
                  {% endfor %}
              </div>
        <!-- pagination -->
        {% include "blogs/pagination_2.html" with page=projects%}
        {% else %}
        <h1> There is no project with the search term "{{query}}" </h1>
        {% endif %}
        </div>

        <div class="col-lg-4">
        {% include "blogs/project_searchForm.html" %}
      {% include "blogs/project_widget.html" %}
      </div>


        </div>
    </div>
</section>

{% endblock %}

tuto10/blogs/templates/blogs/project_searchForm.html
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header">Search</div>
                <div class="card-body">
                  <form method='GET' class='' action="{% url 'blogs:project_search'%}">
                      <input type="text" name="query" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                      <button type="submit"><i class="fas fa-search"></i></button>
                  </form>
                </div>
            </div>

tuto10/blogs/templates/blogs/project_widget.html
{% load blog_tags %}
<div class="card mb-4">
    <div class="card-header">Categories</div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <ul class="list-unstyled mb-0">
                    {% show_list_projectcategory as categories %}
                    {% for category in categories %}
                    <li><a href="{% url 'blogs:portfolio' category.name 'all'%}">{{category.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="card mb-4">
    <div class="card-header">Clients</div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <ul class="list-unstyled mb-0">
                    {% show_list_projectclient as clients %}
                    {% for client in clients %}
                    <li><a href="{% url 'blogs:portfolio' 'all' client.name %}">{{client.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

tuto10/blogs/templates/blogs/service.html
{% extends "blogs/base.html" %}

{% block content %}

<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">Welcome To Our Service!</div>
    </div>
</header>
<!-- Services-->
<section class="page-section" id="services">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Services</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <div class="row text-center">
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-shopping-cart fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="my-3">E-Commerce</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="my-3">Responsive Design</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-lock fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="my-3">Web Security</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

tuto10/blogs/templates/blogs/team.html
{% extends "blogs/base.html" %}

{% block content %}

<!-- Masthead-->
<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">Welcome To Our Team!</div>
    </div>
</header>

<!-- Team-->
<section class="page-section bg-light" id="team">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Our Amazing Team</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <div class="row">
          {% if teams %}
            {% for team in teams %}
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="{{team.image.url}}" alt="..." />
                    <h4>{{team.last_name}} {{team.first_name}}</h4>
                    <p class="text-muted">{{team.job}}</p>
                    <a class="btn btn-dark btn-social mx-2" href="{{team.twitter_url}}"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="{{team.facebook_url}}"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="{{team.linkedin_url}}"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p> There is no team</p>
            {% endif %}

        <!-- pagination -->
        <!-- pagination -->
        {% include "blogs/pagination_1.html" %}    

        </div>
    </div>
</section>


{% endblock %}